name: Gerar sessão Instaloader

on:
  workflow_dispatch:

jobs:
  gerar-sessao:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar Instaloader
        run: pip install instaloader

      - name: Gerar sessão
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        run: |
          instaloader -l "$IG_USERNAME" --password "$IG_PASSWORD"
          mv "$IG_USERNAME".session session-sojjoel

      - name: Commitar sessão
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add session-sojjoel
          git commit -m "Nova sessão gerada automaticamente" || echo "Nada para commitar"
          git push
